
dist: bionic
language: python

jobs:
  include:
  - os: linux
    script:
      - python3 setup.py install
      - python3 -m caanalyzer
      - python3 -c 'import caanalyzer ; caanalyzer.analyze(".")'

